import { Card, CardActionArea, CardContent } from '@mui/material';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Box from "@mui/material/Box";

export default function Home() {

  const arrList = [1,2,3,4,5,6,7,8];

  const cardList = (el) => (
    <Card
      key={el}
      variant="outlined"
      sx={{ width: 'max-content'}}
      >
      <CardActionArea>
      <CardContent sx={{ padding: 0 }}>
      <img
        alt='Random Image'
        src={`https://source.unsplash.com/random/200x200?sig=${el}`}
      />
      </CardContent>
      </CardActionArea>
    </Card>
);

  return (
    <div className={styles.container}>
      <Head>
        <title>JWT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
        <main>
          <Box sx={{display: 'flex', flexWrap: 'wrap', gap: '10px'}}>
              {arrList.map(cardList)}
          </Box>
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
    return {
        props: {}, // will be passed to the page component as props
    };
}
